# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Category.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1053, 732)

        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_12.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_12.setDefault(False)
        self.pushButton_12.setFlat(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 3, 4, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_13.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_13.setDefault(False)
        self.pushButton_13.setFlat(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 4, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_14.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_14.setDefault(False)
        self.pushButton_14.setFlat(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 4, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_15.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_15.setDefault(False)
        self.pushButton_15.setFlat(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 4, 3, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_16.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_16.setDefault(False)
        self.pushButton_16.setFlat(False)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 4, 4, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.widget)
        self.pushButton_18.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_18.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_18.setDefault(False)
        self.pushButton_18.setFlat(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 5, 2, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget)
        self.pushButton_17.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_17.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_17.setDefault(False)
        self.pushButton_17.setFlat(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 5, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.widget)
        self.pushButton_19.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_19.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_19.setDefault(False)
        self.pushButton_19.setFlat(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 5, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton.setIconSize(QtCore.QSize(21, 20))
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.widget)
        self.pushButton_20.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_20.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_20.setDefault(False)
        self.pushButton_20.setFlat(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 5, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_2.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_4.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 4, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_7.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_9.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_9.setDefault(False)
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 3, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_5.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_6.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_3.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_8.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_8.setDefault(False)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 4, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_10.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_10.setDefault(False)
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 3, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("color: rgb(55, 81, 255); background-color: rgb(221, 219, 255)")
        self.pushButton_11.setIconSize(QtCore.QSize(21, 20))
        self.pushButton_11.setDefault(False)
        self.pushButton_11.setFlat(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 3, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Категории"))
        self.pushButton_12.setText(_translate("Form", "Четвертый\n"
"лишний"))
        self.pushButton_13.setText(_translate("Form", "апоЖ"))
        self.pushButton_14.setText(_translate("Form", "История"))
        self.pushButton_15.setText(_translate("Form", "Соображай"))
        self.pushButton_16.setText(_translate("Form", "Финский\n"
"оркестр"))
        self.pushButton_18.setText(_translate("Form", "История"))
        self.pushButton_17.setText(_translate("Form", "Антифразы"))
        self.pushButton_19.setText(_translate("Form", "Пословицы"))
        self.pushButton.setText(_translate("Form", "Пословицы"))
        self.pushButton_20.setText(_translate("Form", "Ну, и еще!"))
        self.pushButton_2.setText(_translate("Form", "Закончите \n"
"мысль"))
        self.pushButton_4.setText(_translate("Form", "Путешествия"))
        self.pushButton_7.setText(_translate("Form", "Эмодзи"))
        self.pushButton_9.setText(_translate("Form", "Картинки-\n"
"вопросы"))
        self.pushButton_5.setText(_translate("Form", "Найди общее"))
        self.pushButton_6.setText(_translate("Form", "Я узнаю тебя из\n"
" тысячи"))
        self.pushButton_3.setText(_translate("Form", "Эрудиция и\n"
" смекалка"))
        self.pushButton_8.setText(_translate("Form", "Советское кино"))
        self.pushButton_10.setText(_translate("Form", "Закончите\n"
" мысль"))
        self.pushButton_11.setText(_translate("Form", "Литература"))

