# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CommandTable.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1003, 882)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.LblSell = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LblSell.setFont(font)
        self.LblSell.setObjectName("LblSell")
        self.gridLayout.addWidget(self.LblSell, 0, 2, 1, 2)
        self.LblCmd2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd2.setFont(font)
        self.LblCmd2.setObjectName("LblCmd2")
        self.gridLayout.addWidget(self.LblCmd2, 2, 2, 1, 1)
        self.LblCmd3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd3.setFont(font)
        self.LblCmd3.setObjectName("LblCmd3")
        self.gridLayout.addWidget(self.LblCmd3, 3, 2, 1, 1)
        self.LblCount = QtWidgets.QLabel(Form)
        self.LblCount.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LblCount.setFont(font)
        self.LblCount.setObjectName("LblCount")
        self.gridLayout.addWidget(self.LblCount, 0, 0, 1, 1)
        self.LblCmd4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd4.setFont(font)
        self.LblCmd4.setObjectName("LblCmd4")
        self.gridLayout.addWidget(self.LblCmd4, 4, 2, 1, 1)
        self.LblCmd1 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd1.setFont(font)
        self.LblCmd1.setObjectName("LblCmd1")
        self.gridLayout.addWidget(self.LblCmd1, 1, 2, 1, 1)
        self.SpinCMd12 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCMd12.setFont(font)
        self.SpinCMd12.setObjectName("SpinCMd12")
        self.gridLayout.addWidget(self.SpinCMd12, 12, 3, 1, 1)
        self.SpinCmd11 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd11.setFont(font)
        self.SpinCmd11.setObjectName("SpinCmd11")
        self.gridLayout.addWidget(self.SpinCmd11, 11, 3, 1, 1)
        self.SpinCmd10 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd10.setFont(font)
        self.SpinCmd10.setObjectName("SpinCmd10")
        self.gridLayout.addWidget(self.SpinCmd10, 10, 3, 1, 1)
        self.SpinCmd16 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd16.setFont(font)
        self.SpinCmd16.setObjectName("SpinCmd16")
        self.gridLayout.addWidget(self.SpinCmd16, 16, 3, 1, 1)
        self.SpinCmd14 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd14.setFont(font)
        self.SpinCmd14.setObjectName("SpinCmd14")
        self.gridLayout.addWidget(self.SpinCmd14, 14, 3, 1, 1)
        self.SpinCmd15 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd15.setFont(font)
        self.SpinCmd15.setObjectName("SpinCmd15")
        self.gridLayout.addWidget(self.SpinCmd15, 15, 3, 1, 1)
        self.SpinCmd13 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd13.setFont(font)
        self.SpinCmd13.setObjectName("SpinCmd13")
        self.gridLayout.addWidget(self.SpinCmd13, 13, 3, 1, 1)
        self.SpinCmd1 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd1.setFont(font)
        self.SpinCmd1.setObjectName("SpinCmd1")
        self.gridLayout.addWidget(self.SpinCmd1, 1, 3, 1, 1)
        self.SpinCmd3 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd3.setFont(font)
        self.SpinCmd3.setObjectName("SpinCmd3")
        self.gridLayout.addWidget(self.SpinCmd3, 3, 3, 1, 1)
        self.LblCmd9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd9.setFont(font)
        self.LblCmd9.setObjectName("LblCmd9")
        self.gridLayout.addWidget(self.LblCmd9, 9, 2, 1, 1)
        self.LblCmd13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd13.setFont(font)
        self.LblCmd13.setObjectName("LblCmd13")
        self.gridLayout.addWidget(self.LblCmd13, 13, 2, 1, 1)
        self.SpinCmd5 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd5.setFont(font)
        self.SpinCmd5.setObjectName("SpinCmd5")
        self.gridLayout.addWidget(self.SpinCmd5, 5, 3, 1, 1)
        self.LblCmd14 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd14.setFont(font)
        self.LblCmd14.setObjectName("LblCmd14")
        self.gridLayout.addWidget(self.LblCmd14, 14, 2, 1, 1)
        self.SpinCmd4 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd4.setFont(font)
        self.SpinCmd4.setObjectName("SpinCmd4")
        self.gridLayout.addWidget(self.SpinCmd4, 4, 3, 1, 1)
        self.LblCmd12 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd12.setFont(font)
        self.LblCmd12.setObjectName("LblCmd12")
        self.gridLayout.addWidget(self.LblCmd12, 12, 2, 1, 1)
        self.LblCmd15 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd15.setFont(font)
        self.LblCmd15.setObjectName("LblCmd15")
        self.gridLayout.addWidget(self.LblCmd15, 15, 2, 1, 1)
        self.SpinCmd8 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd8.setFont(font)
        self.SpinCmd8.setObjectName("SpinCmd8")
        self.gridLayout.addWidget(self.SpinCmd8, 8, 3, 1, 1)
        self.SpinCmd6 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd6.setFont(font)
        self.SpinCmd6.setObjectName("SpinCmd6")
        self.gridLayout.addWidget(self.SpinCmd6, 6, 3, 1, 1)
        self.SpinCmd7 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd7.setFont(font)
        self.SpinCmd7.setObjectName("SpinCmd7")
        self.gridLayout.addWidget(self.SpinCmd7, 7, 3, 1, 1)
        self.SpinCmd2 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd2.setFont(font)
        self.SpinCmd2.setObjectName("SpinCmd2")
        self.gridLayout.addWidget(self.SpinCmd2, 2, 3, 1, 1)
        self.LblCmd5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd5.setFont(font)
        self.LblCmd5.setObjectName("LblCmd5")
        self.gridLayout.addWidget(self.LblCmd5, 5, 2, 1, 1)
        self.LblCmd16 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd16.setFont(font)
        self.LblCmd16.setObjectName("LblCmd16")
        self.gridLayout.addWidget(self.LblCmd16, 16, 2, 1, 1)
        self.SpinCmd9 = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpinCmd9.setFont(font)
        self.SpinCmd9.setObjectName("SpinCmd9")
        self.gridLayout.addWidget(self.SpinCmd9, 9, 3, 1, 1)
        self.LblCmd7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd7.setFont(font)
        self.LblCmd7.setObjectName("LblCmd7")
        self.gridLayout.addWidget(self.LblCmd7, 7, 2, 1, 1)
        self.LblCmd6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd6.setFont(font)
        self.LblCmd6.setObjectName("LblCmd6")
        self.gridLayout.addWidget(self.LblCmd6, 6, 2, 1, 1)
        self.LblCmd11 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd11.setFont(font)
        self.LblCmd11.setObjectName("LblCmd11")
        self.gridLayout.addWidget(self.LblCmd11, 11, 2, 1, 1)
        self.LblCmd8 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd8.setFont(font)
        self.LblCmd8.setObjectName("LblCmd8")
        self.gridLayout.addWidget(self.LblCmd8, 8, 2, 1, 1)
        self.LblCmd10 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblCmd10.setFont(font)
        self.LblCmd10.setObjectName("LblCmd10")
        self.gridLayout.addWidget(self.LblCmd10, 10, 2, 1, 1)
        self.BtnDecrease = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnDecrease.setFont(font)
        self.BtnDecrease.setObjectName("BtnDecrease")
        self.gridLayout.addWidget(self.BtnDecrease, 17, 2, 1, 2)
        self.CmdTable = QtWidgets.QTableView(Form)
        self.CmdTable.setMinimumSize(QtCore.QSize(0, 500))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CmdTable.setFont(font)
        self.CmdTable.setObjectName("CmdTable")
        self.gridLayout.addWidget(self.CmdTable, 1, 0, 17, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Счет команд"))
        self.LblSell.setText(_translate("Form", "Продажа карточек"))
        self.LblCmd2.setText(_translate("Form", "Команда 2"))
        self.LblCmd3.setText(_translate("Form", "Команда 3"))
        self.LblCount.setText(_translate("Form", "Текущий счет:"))
        self.LblCmd4.setText(_translate("Form", "Команда 4"))
        self.LblCmd1.setText(_translate("Form", "Команда 1"))
        self.LblCmd9.setText(_translate("Form", "Команда 9"))
        self.LblCmd13.setText(_translate("Form", "Команда 13"))
        self.LblCmd14.setText(_translate("Form", "Команда 14"))
        self.LblCmd12.setText(_translate("Form", "Команда 12"))
        self.LblCmd15.setText(_translate("Form", "Команда 15"))
        self.LblCmd5.setText(_translate("Form", "Команда 5"))
        self.LblCmd16.setText(_translate("Form", "Команда 16"))
        self.LblCmd7.setText(_translate("Form", "Команда 7"))
        self.LblCmd6.setText(_translate("Form", "Команда 6"))
        self.LblCmd11.setText(_translate("Form", "Команда 11"))
        self.LblCmd8.setText(_translate("Form", "Команда 8"))
        self.LblCmd10.setText(_translate("Form", "Команда 10"))
        self.BtnDecrease.setText(_translate("Form", "Вычесть баллы"))

