# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(412, 829)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GBButtons = QtWidgets.QGroupBox(Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GBButtons.setFont(font)
        self.GBButtons.setObjectName("GBButtons")
        self.gridLayout = QtWidgets.QGridLayout(self.GBButtons)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.CB2 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB2.setText("")
        self.CB2.setChecked(True)
        self.CB2.setObjectName("CB2")
        self.gridLayout.addWidget(self.CB2, 3, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.LblCmd = QtWidgets.QLabel(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LblCmd.setFont(font)
        self.LblCmd.setObjectName("LblCmd")
        self.gridLayout.addWidget(self.LblCmd, 1, 2, 1, 1)
        self.LblBtn = QtWidgets.QLabel(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LblBtn.setFont(font)
        self.LblBtn.setObjectName("LblBtn")
        self.gridLayout.addWidget(self.LblBtn, 1, 4, 1, 1)
        self.Btn2 = QtWidgets.QPushButton(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn2.setFont(font)
        self.Btn2.setObjectName("Btn2")
        self.gridLayout.addWidget(self.Btn2, 3, 2, 1, 1)
        self.LblActive = QtWidgets.QLabel(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LblActive.setFont(font)
        self.LblActive.setObjectName("LblActive")
        self.gridLayout.addWidget(self.LblActive, 1, 0, 1, 2)
        self.Btn1 = QtWidgets.QPushButton(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn1.setFont(font)
        self.Btn1.setObjectName("Btn1")
        self.gridLayout.addWidget(self.Btn1, 2, 2, 1, 1)
        self.CB3 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB3.setText("")
        self.CB3.setChecked(True)
        self.CB3.setObjectName("CB3")
        self.gridLayout.addWidget(self.CB3, 4, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CBButton1 = QtWidgets.QComboBox(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton1.setFont(font)
        self.CBButton1.setObjectName("CBButton1")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.CBButton1.addItem("")
        self.gridLayout.addWidget(self.CBButton1, 2, 4, 1, 1)
        self.CB1 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB1.setText("")
        self.CB1.setChecked(True)
        self.CB1.setTristate(False)
        self.CB1.setObjectName("CB1")
        self.gridLayout.addWidget(self.CB1, 2, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CBButton2 = QtWidgets.QComboBox(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton2.setFont(font)
        self.CBButton2.setObjectName("CBButton2")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.CBButton2.addItem("")
        self.gridLayout.addWidget(self.CBButton2, 3, 4, 1, 1)
        self.Btn11 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn11.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn11.setFont(font)
        self.Btn11.setObjectName("Btn11")
        self.gridLayout.addWidget(self.Btn11, 12, 2, 1, 1)
        self.CBButton5 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton5.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton5.setFont(font)
        self.CBButton5.setObjectName("CBButton5")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.CBButton5.addItem("")
        self.gridLayout.addWidget(self.CBButton5, 6, 4, 1, 1)
        self.CB6 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB6.setEnabled(True)
        self.CB6.setText("")
        self.CB6.setObjectName("CB6")
        self.gridLayout.addWidget(self.CB6, 7, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CBButton4 = QtWidgets.QComboBox(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton4.setFont(font)
        self.CBButton4.setObjectName("CBButton4")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.CBButton4.addItem("")
        self.gridLayout.addWidget(self.CBButton4, 5, 4, 1, 1)
        self.CB7 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB7.setEnabled(True)
        self.CB7.setText("")
        self.CB7.setObjectName("CB7")
        self.gridLayout.addWidget(self.CB7, 8, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CBButton7 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton7.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton7.setFont(font)
        self.CBButton7.setObjectName("CBButton7")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.CBButton7.addItem("")
        self.gridLayout.addWidget(self.CBButton7, 8, 4, 1, 1)
        self.CB8 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB8.setEnabled(True)
        self.CB8.setText("")
        self.CB8.setObjectName("CB8")
        self.gridLayout.addWidget(self.CB8, 9, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.Btn4 = QtWidgets.QPushButton(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn4.setFont(font)
        self.Btn4.setObjectName("Btn4")
        self.gridLayout.addWidget(self.Btn4, 5, 2, 1, 1)
        self.Btn5 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn5.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn5.setFont(font)
        self.Btn5.setObjectName("Btn5")
        self.gridLayout.addWidget(self.Btn5, 6, 2, 1, 1)
        self.Btn9 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn9.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn9.setFont(font)
        self.Btn9.setObjectName("Btn9")
        self.gridLayout.addWidget(self.Btn9, 10, 2, 1, 1)
        self.CB10 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB10.setText("")
        self.CB10.setObjectName("CB10")
        self.gridLayout.addWidget(self.CB10, 11, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CB11 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB11.setText("")
        self.CB11.setObjectName("CB11")
        self.gridLayout.addWidget(self.CB11, 12, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.Btn8 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn8.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn8.setFont(font)
        self.Btn8.setObjectName("Btn8")
        self.gridLayout.addWidget(self.Btn8, 9, 2, 1, 1)
        self.Btn3 = QtWidgets.QPushButton(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn3.setFont(font)
        self.Btn3.setObjectName("Btn3")
        self.gridLayout.addWidget(self.Btn3, 4, 2, 1, 1)
        self.CBButton3 = QtWidgets.QComboBox(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton3.setFont(font)
        self.CBButton3.setObjectName("CBButton3")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.CBButton3.addItem("")
        self.gridLayout.addWidget(self.CBButton3, 4, 4, 1, 1)
        self.Btn10 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn10.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn10.setFont(font)
        self.Btn10.setObjectName("Btn10")
        self.gridLayout.addWidget(self.Btn10, 11, 2, 1, 1)
        self.Btn12 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn12.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn12.setFont(font)
        self.Btn12.setObjectName("Btn12")
        self.gridLayout.addWidget(self.Btn12, 13, 2, 1, 1)
        self.Btn6 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn6.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn6.setFont(font)
        self.Btn6.setObjectName("Btn6")
        self.gridLayout.addWidget(self.Btn6, 7, 2, 1, 1)
        self.CBButton11 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton11.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton11.setFont(font)
        self.CBButton11.setObjectName("CBButton11")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.CBButton11.addItem("")
        self.gridLayout.addWidget(self.CBButton11, 12, 4, 1, 1)
        self.CB12 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB12.setText("")
        self.CB12.setObjectName("CB12")
        self.gridLayout.addWidget(self.CB12, 13, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CBButton12 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton12.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton12.setFont(font)
        self.CBButton12.setObjectName("CBButton12")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.CBButton12.addItem("")
        self.gridLayout.addWidget(self.CBButton12, 13, 4, 1, 1)
        self.CBButton6 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton6.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton6.setFont(font)
        self.CBButton6.setObjectName("CBButton6")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.CBButton6.addItem("")
        self.gridLayout.addWidget(self.CBButton6, 7, 4, 1, 1)
        self.Btn7 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn7.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn7.setFont(font)
        self.Btn7.setObjectName("Btn7")
        self.gridLayout.addWidget(self.Btn7, 8, 2, 1, 1)
        self.CB9 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB9.setText("")
        self.CB9.setObjectName("CB9")
        self.gridLayout.addWidget(self.CB9, 10, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CB5 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB5.setEnabled(True)
        self.CB5.setText("")
        self.CB5.setObjectName("CB5")
        self.gridLayout.addWidget(self.CB5, 6, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CBButton10 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton10.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton10.setFont(font)
        self.CBButton10.setObjectName("CBButton10")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.CBButton10.addItem("")
        self.gridLayout.addWidget(self.CBButton10, 11, 4, 1, 1)
        self.CB4 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB4.setText("")
        self.CB4.setChecked(True)
        self.CB4.setObjectName("CB4")
        self.gridLayout.addWidget(self.CB4, 5, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CBButton8 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton8.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton8.setFont(font)
        self.CBButton8.setObjectName("CBButton8")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.CBButton8.addItem("")
        self.gridLayout.addWidget(self.CBButton8, 9, 4, 1, 1)
        self.CBButton9 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton9.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton9.setFont(font)
        self.CBButton9.setObjectName("CBButton9")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.CBButton9.addItem("")
        self.gridLayout.addWidget(self.CBButton9, 10, 4, 1, 1)
        self.CBButton15 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton15.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton15.setFont(font)
        self.CBButton15.setObjectName("CBButton15")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.CBButton15.addItem("")
        self.gridLayout.addWidget(self.CBButton15, 16, 4, 1, 1)
        self.Btn13 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn13.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn13.setFont(font)
        self.Btn13.setObjectName("Btn13")
        self.gridLayout.addWidget(self.Btn13, 14, 2, 1, 1)
        self.CBButton16 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton16.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton16.setFont(font)
        self.CBButton16.setObjectName("CBButton16")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.CBButton16.addItem("")
        self.gridLayout.addWidget(self.CBButton16, 17, 4, 1, 1)
        self.CB14 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB14.setText("")
        self.CB14.setObjectName("CB14")
        self.gridLayout.addWidget(self.CB14, 15, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CBButton13 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton13.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton13.setFont(font)
        self.CBButton13.setObjectName("CBButton13")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.CBButton13.addItem("")
        self.gridLayout.addWidget(self.CBButton13, 14, 4, 1, 1)
        self.Btn16 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn16.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn16.setFont(font)
        self.Btn16.setObjectName("Btn16")
        self.gridLayout.addWidget(self.Btn16, 17, 2, 1, 1)
        self.CB15 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB15.setText("")
        self.CB15.setObjectName("CB15")
        self.gridLayout.addWidget(self.CB15, 16, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.CB13 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB13.setText("")
        self.CB13.setObjectName("CB13")
        self.gridLayout.addWidget(self.CB13, 14, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.Btn14 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn14.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn14.setFont(font)
        self.Btn14.setObjectName("Btn14")
        self.gridLayout.addWidget(self.Btn14, 15, 2, 1, 1)
        self.CBButton14 = QtWidgets.QComboBox(self.GBButtons)
        self.CBButton14.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CBButton14.setFont(font)
        self.CBButton14.setObjectName("CBButton14")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.CBButton14.addItem("")
        self.gridLayout.addWidget(self.CBButton14, 15, 4, 1, 1)
        self.Btn15 = QtWidgets.QPushButton(self.GBButtons)
        self.Btn15.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn15.setFont(font)
        self.Btn15.setObjectName("Btn15")
        self.gridLayout.addWidget(self.Btn15, 16, 2, 1, 1)
        self.CB16 = QtWidgets.QCheckBox(self.GBButtons)
        self.CB16.setText("")
        self.CB16.setObjectName("CB16")
        self.gridLayout.addWidget(self.CB16, 17, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.LblInstruction = QtWidgets.QLabel(self.GBButtons)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LblInstruction.setFont(font)
        self.LblInstruction.setObjectName("LblInstruction")
        self.gridLayout.addWidget(self.LblInstruction, 0, 0, 1, 5)
        self.verticalLayout.addWidget(self.GBButtons)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.GBTimer = QtWidgets.QGroupBox(Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GBTimer.setFont(font)
        self.GBTimer.setObjectName("GBTimer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GBTimer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SpinBefore = QtWidgets.QSpinBox(self.GBTimer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBefore.setFont(font)
        self.SpinBefore.setMinimum(1)
        self.SpinBefore.setMaximum(1000)
        self.SpinBefore.setSingleStep(1)
        self.SpinBefore.setProperty("value", 5)
        self.SpinBefore.setObjectName("SpinBefore")
        self.gridLayout_2.addWidget(self.SpinBefore, 2, 1, 1, 1)
        self.LblLength = QtWidgets.QLabel(self.GBTimer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblLength.setFont(font)
        self.LblLength.setObjectName("LblLength")
        self.gridLayout_2.addWidget(self.LblLength, 1, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 3, 1, 1)
        self.LblSecBefore = QtWidgets.QLabel(self.GBTimer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblSecBefore.setFont(font)
        self.LblSecBefore.setObjectName("LblSecBefore")
        self.gridLayout_2.addWidget(self.LblSecBefore, 2, 2, 1, 1)
        self.LblSec = QtWidgets.QLabel(self.GBTimer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblSec.setFont(font)
        self.LblSec.setObjectName("LblSec")
        self.gridLayout_2.addWidget(self.LblSec, 1, 3, 1, 1)
        self.SpinLength = QtWidgets.QSpinBox(self.GBTimer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinLength.setFont(font)
        self.SpinLength.setMinimum(1)
        self.SpinLength.setMaximum(1000)
        self.SpinLength.setProperty("value", 10)
        self.SpinLength.setObjectName("SpinLength")
        self.gridLayout_2.addWidget(self.SpinLength, 1, 2, 1, 1)
        self.LblSignal = QtWidgets.QLabel(self.GBTimer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblSignal.setFont(font)
        self.LblSignal.setObjectName("LblSignal")
        self.gridLayout_2.addWidget(self.LblSignal, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.GBTimer)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.GBButtons.setTitle(_translate("Settings", "Назначения кнопок"))
        self.LblCmd.setText(_translate("Settings", "Команда"))
        self.LblBtn.setText(_translate("Settings", "Кнопка"))
        self.Btn2.setText(_translate("Settings", "Команда2"))
        self.LblActive.setText(_translate("Settings", "Активна?"))
        self.Btn1.setText(_translate("Settings", "Команда1"))
        self.CBButton1.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton1.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton1.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton1.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton1.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton1.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton1.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton1.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton1.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton1.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton1.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton1.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton1.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton1.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton1.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton1.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.CBButton2.setCurrentText(_translate("Settings", "Кнопка 2"))
        self.CBButton2.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton2.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton2.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton2.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton2.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton2.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton2.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton2.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton2.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton2.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton2.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton2.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton2.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton2.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton2.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton2.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.Btn11.setText(_translate("Settings", "Команда11"))
        self.CBButton5.setCurrentText(_translate("Settings", "Кнопка 5"))
        self.CBButton5.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton5.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton5.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton5.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton5.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton5.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton5.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton5.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton5.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton5.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton5.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton5.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton5.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton5.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton5.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton5.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.CBButton4.setCurrentText(_translate("Settings", "Кнопка 4"))
        self.CBButton4.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton4.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton4.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton4.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton4.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton4.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton4.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton4.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton4.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton4.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton4.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton4.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton4.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton4.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton4.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton4.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.CBButton7.setCurrentText(_translate("Settings", "Кнопка 7"))
        self.CBButton7.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton7.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton7.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton7.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton7.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton7.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton7.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton7.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton7.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton7.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton7.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton7.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton7.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton7.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton7.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton7.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.Btn4.setText(_translate("Settings", "Команда4"))
        self.Btn5.setText(_translate("Settings", "Команда5"))
        self.Btn9.setText(_translate("Settings", "Команда9"))
        self.Btn8.setText(_translate("Settings", "Команда8"))
        self.Btn3.setText(_translate("Settings", "Команда3"))
        self.CBButton3.setCurrentText(_translate("Settings", "Кнопка 3"))
        self.CBButton3.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton3.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton3.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton3.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton3.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton3.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton3.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton3.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton3.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton3.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton3.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton3.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton3.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton3.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton3.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton3.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.Btn10.setText(_translate("Settings", "Команда10"))
        self.Btn12.setText(_translate("Settings", "Команда12"))
        self.Btn6.setText(_translate("Settings", "Команда6"))
        self.CBButton11.setCurrentText(_translate("Settings", "Кнопка 11"))
        self.CBButton11.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton11.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton11.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton11.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton11.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton11.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton11.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton11.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton11.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton11.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton11.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton11.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton11.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton11.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton11.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton11.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.CBButton12.setCurrentText(_translate("Settings", "Кнопка 12"))
        self.CBButton12.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton12.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton12.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton12.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton12.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton12.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton12.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton12.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton12.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton12.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton12.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton12.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton12.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton12.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton12.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton12.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.CBButton6.setCurrentText(_translate("Settings", "Кнопка 6"))
        self.CBButton6.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton6.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton6.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton6.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton6.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton6.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton6.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton6.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton6.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton6.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton6.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton6.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton6.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton6.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton6.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton6.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.Btn7.setText(_translate("Settings", "Команда7"))
        self.CBButton10.setCurrentText(_translate("Settings", "Кнопка 10"))
        self.CBButton10.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton10.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton10.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton10.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton10.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton10.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton10.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton10.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton10.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton10.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton10.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton10.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton10.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton10.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton10.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton10.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.CBButton8.setCurrentText(_translate("Settings", "Кнопка 8"))
        self.CBButton8.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton8.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton8.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton8.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton8.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton8.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton8.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton8.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton8.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton8.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton8.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton8.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton8.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton8.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton8.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton8.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.CBButton9.setCurrentText(_translate("Settings", "Кнопка 9"))
        self.CBButton9.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton9.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton9.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton9.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton9.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton9.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton9.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton9.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton9.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton9.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton9.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton9.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton9.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton9.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton9.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton9.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.CBButton15.setCurrentText(_translate("Settings", "Кнопка 15"))
        self.CBButton15.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton15.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton15.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton15.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton15.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton15.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton15.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton15.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton15.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton15.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton15.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton15.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton15.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton15.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton15.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton15.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.Btn13.setText(_translate("Settings", "Команда13"))
        self.CBButton16.setCurrentText(_translate("Settings", "Кнопка 16"))
        self.CBButton16.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton16.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton16.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton16.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton16.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton16.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton16.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton16.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton16.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton16.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton16.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton16.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton16.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton16.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton16.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton16.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.CBButton13.setCurrentText(_translate("Settings", "Кнопка 13"))
        self.CBButton13.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton13.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton13.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton13.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton13.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton13.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton13.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton13.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton13.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton13.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton13.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton13.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton13.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton13.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton13.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton13.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.Btn16.setText(_translate("Settings", "Команда16"))
        self.Btn14.setText(_translate("Settings", "Команда14"))
        self.CBButton14.setCurrentText(_translate("Settings", "Кнопка 14"))
        self.CBButton14.setItemText(0, _translate("Settings", "Кнопка 1"))
        self.CBButton14.setItemText(1, _translate("Settings", "Кнопка 2"))
        self.CBButton14.setItemText(2, _translate("Settings", "Кнопка 3"))
        self.CBButton14.setItemText(3, _translate("Settings", "Кнопка 4"))
        self.CBButton14.setItemText(4, _translate("Settings", "Кнопка 5"))
        self.CBButton14.setItemText(5, _translate("Settings", "Кнопка 6"))
        self.CBButton14.setItemText(6, _translate("Settings", "Кнопка 7"))
        self.CBButton14.setItemText(7, _translate("Settings", "Кнопка 8"))
        self.CBButton14.setItemText(8, _translate("Settings", "Кнопка 9"))
        self.CBButton14.setItemText(9, _translate("Settings", "Кнопка 10"))
        self.CBButton14.setItemText(10, _translate("Settings", "Кнопка 11"))
        self.CBButton14.setItemText(11, _translate("Settings", "Кнопка 12"))
        self.CBButton14.setItemText(12, _translate("Settings", "Кнопка 13"))
        self.CBButton14.setItemText(13, _translate("Settings", "Кнопка 14"))
        self.CBButton14.setItemText(14, _translate("Settings", "Кнопка 15"))
        self.CBButton14.setItemText(15, _translate("Settings", "Кнопка 16"))
        self.Btn15.setText(_translate("Settings", "Команда15"))
        self.LblInstruction.setText(_translate("Settings", "Нажмите на кнопку с именем команды для автоопределения"))
        self.GBTimer.setTitle(_translate("Settings", "Настройки таймера"))
        self.LblLength.setText(_translate("Settings", "Длительность раунда "))
        self.LblSecBefore.setText(_translate("Settings", "секунд до конца"))
        self.LblSec.setText(_translate("Settings", "секунд"))
        self.LblSignal.setText(_translate("Settings", "Сигнал за"))

